- README.md
- src/app/pages/home/home.page.html
Toggle could be used for tutorial, however we should not show that for the moment as it's confusing for users.
Added note for different IP to be used with Android emulator.
> fix: Disable unimplemented toggle button

- README.md
- package-lock.json
- package.json
- src/mobile-services.js
Master got broken because of:
- Mobile config was enabled and it was overriding the user details
- Package was not released properly
After testing we will release entire js-sdk
> fix: Update sdk package

- server/package.json
https://issues.jboss.org/browse/AEROGEAR-8399
Sample app's server image was already pushed to https://hub.docker.com/r/aerogear/voyager-server-example-task. I used that name in the NPM script.
> AEROGEAR-8399 Push server image to Docker

- config.xml
- package.json
* [AEROGEAR-8431](https://issues.jboss.org/browse/AEROGEAR-8431) - Ionic Example App does not start on Android when keycloak is used
1. Run the server (Instructions on [README](https://github.com/aerogear/voyager-ionic-example/blob/development/README.md#running-the-server))
1. Update the GraphQL ip (probably your machine ip) in [src/app/services/voyager.service.ts](https://github.com/aerogear/voyager-ionic-example/blob/development/src/app/services/voyager.service.ts#L68-L69)
1. Add the Identity manager service info in [mobile-services.js](https://github.com/aerogear/voyager-ionic-example/blob/development/src/mobile-services.js)
```json
{
"id": "<YOUR PROJECT ID>",
"name": "keycloak",
"type": "keycloak",
"url": "<KEYCLOAK URL>",
"config": {
"auth-server-url": "<KEYCLOAK URL>", …
```
> Fix Auth for Android

- .circleci/config.yml
- scripts/publish_example_server_container.sh
- server/push-script.sh
https://issues.jboss.org/browse/AEROGEAR-8437
Automated publishing of `aerogear/voyager-server-example-task` container to Dockerhub.
Tested in my fork https://circleci.com/gh/wojta/voyager-ionic-example/9
> feat: Pushing example server docker container to Dockerhub 

- README.md
- server/openshift-template.yml
OpenShift template for GraphQL Server.
1. Spin up Minishift locally or target OpenShift instance
1. Clone this branch
1. Create new project and run `oc new-app -f server/openshift-template.yml`
1. Verify that created server route in your OpenShift project + GraphQL endpoint (`http://<ionic-route-url>/graphql`) is accessible
> feat: GraphQL server OpenShift template

- src/app/pages/home/home.page.html
Add text wrap to labels on the home page to show full text
> fix:add textwrap to some labels to show full text

- server/Dockerfile
chmod is not required since we mounting volume. 
The volume itself will not support changing permissions.
> fix: remove invalid docker command

- server/src/index.js
- server/src/tasks/schema.js
- src/app/services/sync/graphql.queries.ts
- src/app/services/sync/item.service.ts
Fix compilation issues and lining problems for new JS-SDK after migration to apollo client 2.5. Add explicit version on creation in client. Using explicit version allows us to perform offline updates on the object. This idea is already extended by @StephenCoady in his PR for js-sdk
PR can be verified by changing task offline 2 times and restoring connectivity.
After restoring connectivity no conflict should be seen.
> fix: Add explicit version for content creation

- server/src/files/schema.js
This PR should allow the app to handle the case the file upload directory cannot be created. No changes are necessary to the actual file upload implementation itself right now because an error will already be thrown and returned to the client if the file upload fails.
> fix: handle inability to create file upload directory

- server/openshift-template.yml
Added volume to OpenShift template for Ionic Showcase Server App.
File upload feature doesn't work without persistent storage mounted in server app
```
oc new-project ionic-showcase-server-test
oc new-app -f server/openshift-template.yml
```
Check that there is no warning about missing persistent storage
This PR is related to fix in https://github.com/aerogear/ionic-showcase/pull/90
> fix: add volume to template

- package.json
- src/app/services/sync/cache.updates.ts
- src/app/services/sync/item.service.ts
- src/app/services/sync/voyager.service.ts
Follows new approach from https://github.com/aerogear/aerogear-js-sdk/pull/292
Requires to link js-SDK for the moment.
ticket:
https://issues.jboss.org/browse/AEROGEAR-8333
1. Add new item when offline
2. Restart mobile app (do not work in website version)
3. See item that was added. 
4. Restore network - see that item is still there
> Externalize cache updates to object

- server/src/tasks/schema.js
- src/app/app.component.ts
- src/app/pages/settings/settings.page.ts
- src/app/services/push.service.ts
https://issues.jboss.org/browse/AGMS-187
Push-related fixes
1. When `alert` property wasn't defined in push message, iOS app didn't show received push notification. See https://issues.jboss.org/browse/AGMS-187 for more details
2. Push was not initialised on first app launch
3. Each time settings page was displayed, push registration was triggered - caused by issue with ionToggle - see https://forum.ionicframework.com/t/ion-toggle-ionchange-triggered/139187
> fix: push - registering, sending

- src/app/services/auth.service.ts
- src/app/services/sync/voyager.service.ts
you can watch this video of the verification https://youtu.be/dH9V4o6aZb0
@wtrocki @StephenCoady @danielpassos @wei-lee I believe this fix is good enough. I'd love to know if I'm missing anything. Feel free to try verify with the following config from the community cluster
```
{
"version": 1,
"namespace": "demo",
"clientId": "org.aerogear.ionic.showcase",
"services": [
{
"id": "923e3416-45a3-11e9-9467-0af08791569c",
"name": "keycloak",
"type": "keycloak",
"url": "https://keycloak-route-demo.comm2.skunkhenry.com/auth",
"config": {
"auth-server-url": "https://keycloak-route-demo.comm2.skunkhenry.com/auth",
"confidential-port": 0,
"public-client": true,
"realm": "demo",
"resource": "org.aerogear.ionic.showcase-public",
"ssl-required": "external"
}
},
{
"id": …
```
> fix: clear apollo client cache and localstorage on logout

- package.json
Bump voyager client version from 2.3.1 --> 2.4.0-dev.1
> chore(deps): bump voyager client version

- src/app/app-routing.module.ts
- src/app/pages/files/files.page.html
- src/app/pages/offline-queue/offline-queue.page.html
- src/app/pages/settings/settings.page.html
- src/app/pages/task/task.page.html
- src/app/pages/task/task.page.scss
- Removed disabled state of Offline Changes button
- Removed white space on Task and Queue pages if there are no items
- Changed File Management title
- Removed unnecessary section from Settings page
- Removed redundant routing
> fix: small layout and wording changes

- src/app/pages/offline-queue/offline-queue.page.html
- src/app/pages/offline-queue/offline-queue.page.scss
- src/app/pages/task/task.page.html
- src/app/pages/task/task.page.scss
- src/global.scss
Unnecessary white strip showing for empty `ion-list` on Task and Offline Queue pages.
Before:
After:
> Fix: empty list UI issue for MD

- src/app/app.component.html
- src/app/pages/home/home.page.html
- src/global.scss
- Separate icons for Device Security and Settings
- Border bottom of menu to reach edge
Before: 
After:
> fix: menu and home UI

- .gitignore
- README.adoc
- server/package.json
- server/scripts/keycloak/docker-compose.yml
- server/scripts/keycloak/initKeycloak.js
- server/scripts/keycloak/realm-export.json
This PR makes working locally with keycloak + the showcase app really easy.
* adds a `npm run keycloak` command that starts a keycloak server (using docker-compose)
* adds a `npm run keycloak:init` command that imports a realm, creates roles + users and generates the config needed for the server (`keycloak.json`) and the service config (`mobile-services.json`) for the mobile application.
There are steps for setting up the keycloak integration in the readme.
* Follow the steps in the readme to 
* spin up keycloak
* run the `keycloak:init` script
* copy the appropriate configs into the correct location.
* Start the server and the app
* You should be brought to the keycloak login screen
* You can log in with either `developer/developer` or `admin/admin`
> feat: tools to simplify local keycloak setup

- src/app/pages/task/task.page.html
- src/app/pages/task/task.page.ts
- src/app/services/sync/item.service.ts
Disable local filtering as it is affecting performance local performance tests and not giving any graphql oriented capability.
Every time new item is added local filter gets triggered that contributes to reduced performance for a really large number of items in offline queue
> fix: disable task filtering

- .circleci/config.yml
Currently, the build-android job in CireclCI [1] fails because the pipeline restores old Cordova plugins before building the app, and Cordova is not smart enough to delete obsolete plugins from the plugins directory for this reason we should restore plugins from the cache only if the config.xml didn't change from the last build.
> Fix android build CircleCI job

- network_security_config.xml
Starting with Android 9 clear text communication (http, ws) between the client app and the server is disabled by default.
Most of the user will start the ionic-showcase server locally without any tls certificate (https), and if then they deploy the android app to an android emulator or a real device with android 9 or greater they will have this error in the console `ERR_CLEARTEXT_NOT_PERMITTED`.
I would like to globally enable clear text communication in order to make it more simple to new users to try the ionic-showcase on all devices. 
An alternative solution to this problem is to document in the README how to globally enable clear text [1] or how to do it only for specific domains [2].
1. https://developer.android.com/training/articles/security-config#base-config
2. …
> Allow clear text communication also in Android 9 and above

- README.adoc
- server/package.json
- server/src/subscriptions.js
* I noticed `npm run start` was using `nodemon`. The showcase container image was running the app using nodemon (not very good)
* I changed `npm run start` to start with node
* I added `npm run dev` to start with `MQTT_HOST=localhost nodemon`
* The server no longer defaults to `localhost` when no `MQTT_HOST` is set. Instead it will default to an in memory pubsub
* While running locally, you can start with `npm start` or `node src/index.js` and by default you will get in memory pubsub
* While running locally, you can start with `npm run dev` or `MQTT_HOST=localhost node src/index.js` to get MQTT Pubsub
> fix: use in memory pubsub when no MQTT_HOST set

- .circleci/config.yml
Gradle's docs recommend using some package manager called SDKman. https://docs.gradle.org/current/userguide/installation.html#installing_with_a_package_manager
My guess is they have started distributing their releases through that and stopped distributing through traditional package managers like `apt`, `dnf` etc.
I verified this PR myself by rerunning the failed build with SSH and performing all the steps manually. This resulted in a successful build.
> ci: use recommended approach for installing gradle

- .circleci/config.yml
It turns out CircleCI runs each command in its own sandbox so we need to run these sdkman related commands together.
> ci: fix sdkman installation in android build

- src/app/services/sync/voyager.service.ts
@jhellar I think this fixes the bug you found in the showcase. It was a race condition between keycloak being initialised over the network and the apollo client being created and firing offline mutations too quickly.
Do you think you could try this out for me on a device and see if it works? I have checked against the cluster you gave me yesterday and I can't reproduce the bug with this fix.
> fix: wait for auth to be initialised

- package.json
- src/app/pages/apptrust/apptrust.page.html
- src/app/pages/apptrust/apptrust.page.ts
fix for https://issues.jboss.org/browse/AGMS-662
- clone the ionic-showcase https://github.com/aerogear/ionic-showcase
- checkout this branch 
- change the mobile-services.json to 
```json
{
"version": 1,
"namespace": "voyager",
"clientId": "voyager-ionic-example",
"services": [
{
"id": "security",
"name": "security",
"type": "security",
"url": "https://route-mobile-security-service.apps.mdsdemo-710a.openshiftworkshop.com/"
}
]
}
```
- install
```bash
npm i
npm run start
````
- check that the warning is displayed in the web
- run an android build 
```bash
ionic cordova build android
```
- copy the apk file to an android emulator 
- Check to see if the app trust page loads as expected
> Isnotcordova

- src/app/pages/profile/profile.page.ts
- src/app/services/auth.service.ts
Our mobile config requires setting up valid redirect urls and web orgins. 
Without that application will not work properly.
Without this change, showcase was failing miserably with the white screen if keycloak was initialized with wrong values.
After this change devs are notified in the console:
and UI:
> Manifest keycloak invalid configuration in UI and console

- server/src/index.js
Right now I'm working on this issue: https://issues.jboss.org/browse/AEROGEAR-9693
As part of that I'm moving the showcase openshift template towards using an official Red Hat Node.js image. This image explicitly sets NODE_ENV=production which disables introspection.
> fix: explicitly enable introspection

- e2e/protractor.conf.js
- e2e/src/app.e2e-spec.ts
When running the e2e tests in a loop forever they usually fail after ~10 executions because protractor is injected before angular is loaded.
By sleep 1s before starting all tests we give time to Angular to load correctly. 1s is enough time for Angular to set the `window.angular` variable and then protractor will take care of waiting for all angular services to be loaded.
In order to ensure that 1s is enough I've executed again all tests in loop for more the 2h ( ~100 executions ) without having any issues
> Fix E2E flaky tests

- package.json
In README it is recommended to install ionic version 4, but in package.json there is ionic@5. For me this broke `npm run ionic:android`:
```
➜  ionic-showcase git:(master) npm run ionic:android
> ionic4-graphql-starter-app@1.0.0 ionic:android /Users/jhellar/work/repos/ionic-showcase
> ionic cordova run android
[ERROR] native-run was not found on your PATH. Please install it globally:
npm i -g native-run
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic4-graphql-starter-app@1.0.0 ionic:android: `ionic cordova run android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic4-graphql-starter-app@1.0.0 ionic:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm …
```
> fix ionic version

- .circleci/config.yml
Apparently this feature is now a paid feature and it's causing jobs on master to fail.
https://circleci.com/gh/aerogear/ionic-showcase/1557?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Removing it to see will those jobs start passing again.
> fix: stop using docker layer caching

- .circleci/config.yml
Build has been failing for a while and since we moving to PWA having android build makes less sense now.
> fix: Remove outdated Android build

- .circleci/config.yml
- package.json
- server/package.json
Early test to check circleci.
Generally graphback will have server in typescript so current build is disabled for that purpose. 
I wanted to do piping first
> fix: Build server and client

- client/src/config/clientConfig.ts
This PR makes it possible to point the client app to a given server url (specified at build time)
Examples of how this works with our current npm scripts
```
REACT_APP_SERVER_URL=https://some-domain.com/graphql yarn start
```
or
```
REACT_APP_SERVER_URL=https://some-domain.com/graphql yarn build
```
There's a little bit of cleverness there to set the websocket url based on the http url provided also. This is a pretty canonical way to do this in react applications over static config files that are being checked into the repo. See https://create-react-app.dev/docs/adding-custom-environment-variables/
> fix: add ability to define server url at build time

- server/src/graphql.ts
Disable validation for schema so we can load it with directives that are not supplied. There are follow up issues that I will need to resolve later:
- Add error code to keycloak lib
- Show actual dialog to user that error happened
Follow the local walkthought for keycloak (add hasRole)
> fix: Enable directives in result schema

- client/package.json
- client/src/forms/TaskForm.js
- client/src/forms/schema.js
- client/src/pages/AddTaskPage.tsx
- client/src/pages/UpdateTaskPage.tsx
- server/package.json
> Add uniforms to starter app
