aerogear/datasync-starter

config.xml, package-lock.json, package.json, src/app/pages/home/home.page.ts
Depends on https://github.com/aerogear/aerogear-js-sdk/pull/184
| iOS  | Android  |
|:-:|:-:|
| iPhone 8 (iOS 12.1.1) | Pixel (Android 9) |
| ![ionic-ios](https://user-images.githubusercontent.com/13337/49944184-09277180-fed1-11e8-95ca-6750f9624e37.gif) | ![ionic-android](https://user-images.githubusercontent.com/13337/49944070-ac2bbb80-fed0-11e8-86f7-1da104b0ea7a.gif)|
=> Network status cordova ios

README.md, package.json, server/src/schema.js, src/app/app-routing.module.ts, src/app/pages/home/home.page.html, src/app/pages/home/home.page.ts, src/app/pages/new-item/new-item.page.ts, src/app/pages/update-item/update-item.page.ts, src/app/services/item.service.ts
Example of optimistic responses.
=> Optimistic responses

package-lock.json, package.json, src/app/app-routing.module.ts, src/app/pages/home/home.page.ts, src/app/services/item.service.ts
WIP.. Need to add cache updates
=> Subscriptions cache

package-lock.json, server/package-lock.json, server/package.json, server/src/index.js
It works when using linked version. When using released version it seems that we are missing some files
=> integrate with voyager server

server/package-lock.json, server/package.json, server/src/schema.js
Integrate with the conflict package.
1. Link conflict package (pending publishing)
2. Start server
3. Copy example graphql queries (playground is broken, not sure why)
4. Make query with the right version to update data
4. New object with new version is returned
5. Make the same query again
=> feat: integrate server with conflict package

server/src/index.js, src/app/services/voyager.service.ts
Can be used to play with https://github.com/aerogear/aerogear-js-sdk/pull/196
Really raw version for testing.
=> Conflicts resolution integration

package-lock.json, package.json, src/app/services/graphql.queries.ts, src/app/services/voyager.service.ts
Cannot get that to work. Leaving for the moment because of the deadlines.
=> feat: add snackbar on conflict

README.md, package-lock.json, package.json, server/src/config/keycloak.json, src/app/pages/home/home.page.html, src/app/pages/home/home.page.ts, src/app/services/auth.service.ts, src/app/services/openshift.service.ts, src/app/services/voyager.service.ts, src/mobile-services.js
Added login/logout/getProfile capacity
Sync integration:
Outstanding - while this work js-sdk sync package needs some refactoring as api do not allow to refresh token properly. Going to work on this
=> feat: Keycloak integration

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, .github/ISSUE_TEMPLATE/3-ask-for-help.md, .github/PULL_REQUEST_TEMPLATE.md
=> feat: add some github templates

package.json
=> fix: bump versions of js-sdk components

src/app/services/auth.service.ts
=> fix: wrap tokenUpdate call into a promise

.circleci/config.yml, .gitignore
Small PR to add build to circleCI.
=> Improve development

package.json, src/app/services/auth.service.ts, src/app/services/graphql.queries.ts, src/app/services/item.service.ts, src/app/services/network.service.ts, src/app/services/openshift.service.ts, src/app/services/types.ts, src/app/services/voyager.service.ts
Bump and integrate with RC3 release of the client.
Testing efforts:
I'm going to cover testing, but also looking for volunteers to test things again.
Once this is done I will merge dev to master.
=> Migrate to new RC3 release

package.json, src/app/pages/home/home.page.html, src/app/pages/home/home.page.ts
https://issues.jboss.org/browse/AEROGEAR-8433
https://issues.jboss.org/browse/AEROGEAR-8489
1. Clone this branch
2. `npm install`
3. Use this URL for server in  `src/app/services/voyager.service.ts`:
```
options.httpUrl = 'https://voyager-ionic-example-test.comm2.skunkhenry.com/graphql';
options.wsUrl = 'wss://voyager-ionic-example-test.comm2.skunkhenry.com/graphql';
```
4. Add keycloak configuration to `src/mobile-services.js` (ping me)
5. Run `npm run ionic:android`, login and verify the functionality of app
6. Do the same for iOS (`npm run ionic:ios`)
* [this fix](https://github.com/aerogear/voyager-ionic-example/pull/46/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13) was taken from [here](https://forum.ionicframework.com/t/fresh-ionic-fails-to-emulate-ios-12-info-plist-file-not-found/1 …
=> Fix Auth & iOS build

src/app/pages/security/security.page.ts
=> Fixed platform detection

src/app/app.component.html, src/app/app.component.ts, src/app/pages/files/files.page.html, src/app/pages/files/files.page.ts, src/app/pages/home/home.page.html, src/app/pages/task/task.page.html, src/app/pages/task/task.page.ts, src/app/services/auth.service.ts, src/app/services/file/graphql.queries.ts, src/app/services/sync/item.service.ts, src/global.scss
Splitting work into smaller PR to simplify review. 
This set of changes are fixing major bugs in current app mostly about error handling.
Added gui methods for reporting server side issues:
Improved home page
Added error handling for tasks
Notes: I could not make onlineOnly annotation to work. Logged bug:
https://issues.jboss.org/browse/AEROGEAR-8538
=> Showcase improvements

server/package.json, server/src/config/config.js, server/src/index.js, server/src/tasks/schema.js
small PR to add push integration to example server.
* Add push-config.json file to the config folder of the server.
* It should contain the fields "url", "applicationId" and "masterSecret"
* Run the server and create some tasks using localhost:4000:/graphql
* You should see confirmation in the console
* The notifications should reach UPS
=> feat:added push integration to server

src/app/pages/docs/docs.page.html, src/app/pages/home/home.page.html
Provide docs page that will draft intentions and list all services.
=> docs: Showcase documentation for all services

src/app/pages/home/home.page.html, src/app/pages/home/home.page.scss, src/app/pages/profile/profile.page.html, src/app/pages/profile/profile.page.ts, src/global.scss
Set of minor fixes.
UI improvement:
Removing profile data after pressing logout/login
=> Small fixes - part 2 :)

config.xml, package.json, server/src/tasks/schema.js, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/pages/home/home.page.html, src/app/pages/home/home.page.ts, src/app/pages/settings/settings.module.ts, src/app/pages/settings/settings.page.html, src/app/pages/settings/settings.page.spec.ts, src/app/pages/settings/settings.page.ts, src/app/services/push.service.ts, src/mobile-services.js
Issue [AEROGEAR-8488](https://issues.jboss.org/browse/AEROGEAR-8488)
Added UPS integration to the `ionic-showcase`.
Now, if the app is closed when a change is done on the server, a notification is received on the client.
Clicking on the notification, will open the app and will move to the tasks page.
- Added UPS integration
- Renamed package to `org.aerogear.ionic.showcase`
- Created app in Firebase with package `org.aerogear.ionic.showcase`
- Created app `ionic-showcase` with android variant in the community cluster UPS
- Added a simple `settings` page that allow to enable/disable push notifications
1. Add `google-services.json` file into the root of the project
2. add push-config.json into the `server/src/config folder`
3. add push-service configuration to the `mobile-services.js` file. …
=> Added UPS integration

server/files/test.doc, server/src/files/ddl.js
Drop sample file that was used for testing
=> fix: remove sample file

src/app/pages/settings/settings.page.ts
https://issues.jboss.org/browse/AEROGEAR-8591
1. Clone this branch
2. Run `npm i`
3. Edit `src/mobile-services.js` file - feel free to use [mobile-services configuration from this project](https://comm2.skunkhenry.com:8443/console/project/test/overview)
4. Run the app: `npm run start` (or maybe better to test this on mobile device as well)
5. In app, go to **Settings**
Make sure the push notification is enabled (switch is ON - blue)
=> fix: enable push on a first app launch

config.xml, package.json
Verification instructions https://issues.jboss.org/browse/AEROGEAR-8585
=> AEROGEAR-8585 Save metrics plugin in config

README.md
This is a low priority PR so don't feel you need to spend ages today reviewing it. The title describes it all.
=> fix: minor typos and clarifications to the readme

src/app/pages/home/home.page.scss
=> fix: minor styling fix

src/app/services/sync/voyager.service.ts
=> fix: ensure authContextProvider is not used when auth is disabled

server/package.json
Add missing dependency for altair
=> fix: add missing dependency

src/app/pages/security/security.page.html
For some reason the device score was removed. I was talking to Nano and she said it would be nice to have back. cc @wei-lee
=> re-add device score percentage

README.adoc
https://issues.jboss.org/browse/AGMS-286
=> voyager.service.ts#L42 url is rendering as a 404

README.adoc
notifications don't work in emulator
=> add push note

src/app/app.component.html, src/app/pages/about/docs.page.html, src/app/pages/home/home.page.html
https://issues.jboss.org/browse/AEROGEAR-8693
merging to a feature branch 
Rename the device security section and change its references in the home and about page  
- pull this pr
- npm i
- run `ionic serve`
- check the follow sections to see the change
- menu
- Home screen
- About screen
=> feat(app-security): replace device security with security (AEROGEAR-8693)

src/app/pages/offline-queue/offline-queue.page.html, src/app/pages/offline-queue/offline-queue.page.ts, src/app/pages/task/task.page.html, src/app/pages/task/task.page.scss, src/app/pages/task/task.page.ts, src/app/services/sync/item.service.ts
=> feat: add ability to filter

package.json, src/app/components/offline.notifier.ts, src/app/pages/new-item/new-item.page.ts, src/app/pages/update-item/update-item.page.ts, src/app/services/network.service.ts
Implement new API from https://github.com/aerogear/aerogear-js-sdk/pull/327
Requires code to be linked. 
ping @piccolazucca once this is done we can also connect storage properly.
New API will not block mutation anymore and it will allow developers to get instant feedback when offline.
=> Offline non blocking

src/app/pages/apptrust/apptrust.page.html, src/app/pages/apptrust/apptrust.page.ts
Add a page to the ionic-showcase app to demo the App Trust functionality 
feed back on ui
- clone mobile security service https://github.com/aerogear/mobile-security-service
- cd to the repo 
- start the db 
```bash
docker-compose up -d db
```
- start the server
```bash
make serve
```
- clone the ionic-showcase https://github.com/aerogear/ionic-showcase
- cd to the repo
- checkout this branch `AEROGEAR-8690`
- change the mobile-services.js to 
```js
let config = {
"version": 1,
"namespace": "voyager",
"clientId": "voyager-ionic-example",
"services": [
{
"id": "security",
"name": "security",
"type": "security",
"url": "http://10.0.2.2:3000",
"config": {
"mobile-security-server-url": "http://10.0.2.2:3000"
}
}
]
};
module.exports = config;
```
- install
```bash
npm i
````
- run an android …
=> feat(app-security): update the wording

package.json, server/src/tasks/schema.js, server/src/tasks/subscriptions.js, src/app/services/sync/cache.updates.ts, src/app/services/sync/graphql.queries.ts, src/app/services/sync/item.service.ts, src/app/services/sync/types.ts, src/app/services/sync/voyager.service.ts
This PR may not need to be merged.
It breaks our subscriptions on the server into individual subscriptions so that the helpers are cleaner and do not run multiple times.
=> feat: added multiple subscriptions. using helpers now also.

src/app/services/push.service.ts
Make the showcase register the devices in 2 UnifiedPush Server categories ("ionic" and "showcase")
=> Add categories for the push registration

README.adoc
Currently the application is not working with Cordova 9. This will help avoid issues temporarily until #194 is solved.
=> docs: use cordova 8

package.json
This PR allow the Android devices to receive messages from the UPS using categories or without any criteria. 
For more info see: https://github.com/aerogear/aerogear-js-sdk/pull/362
=> Update push dependency

server/src/tasks/subscriptions.js
Summary of Changes:
* fix: use more AMQ friendly topic names for subscriptions
This naming convention simplifies the configuration of queues/topics in AMQ Online which is one of our target environments.
It should  allow us to only create a single queue / topic in AMQ Online. Then as part of installation, we will create a single queue called `tasks`
and then we will get `tasks/added`, `tasks/deleted` and `tasks/updated` for free.
=> Enmasse resources.yml

.circleci/config.yml, README.adoc, config.xml, package.json
Removed `cordova-plugin-iroot` and installed `@aerogear/cordova-plugin-iroot` @  version `0.8.1` which include the fix for compatibility issues with cordova 9 [1]
1. https://issues.jboss.org/browse/AEROGEAR-9087
1. Check out the branch
2. Update Cordova to 9 `npm install -g cordova@9`
3. Build android or ios app `ionic cordova build android`
=> AEROGEAR-9323 Migrate to iroot aerogear fork

package.json, src/app/app.module.ts, src/app/services/push.service.ts
This PR remove all phonegap-push-plugin code which was moved to JS-SDK release on version [2.5.1-dev.2](https://www.npmjs.com/package/@aerogear/push/v/2.5.1-dev.2)
=> Remove phonegap-push-plugin code

.circleci/config.yml, package.json
=> Update nodejs version for circleci builds

.circleci/config.yml
=> ci: gradle installation issues in ci

src/app/pages/new-item/new-item.page.ts, src/app/pages/update-item/update-item.page.ts
=> fix: only allow strings below 250 chars for title + desc

.factory.json
Followed recent documentation to create factory
See: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.0/html/administration_guide/administering_workspaces#creating_factories
CodeReady do not support other branch than master so:
1. Login to codeready
1. Go to factories screen 
2. Go to create factory screen (/dashboard/#/factories/create-factory)
3. Choose template
4. Copy content of this file
5. Select create workspace from factory
=> fix: update codeready commands

src/app/services/auth.service.ts, src/mobile-services.json
fixes: https://issues.jboss.org/browse/AEROGEAR-9734
=> Fix logout

src/app/pages/task/task.page.ts, src/app/services/sync/voyager.service.ts
=> fix: issue with offline queue

package.json
This should fix issue https://issues.jboss.org/browse/INTLY-3619
=> fix: add ionic as a dev dependency

package.json, src/app/pages/task/task.page.ts, src/app/services/sync/item.service.ts, src/app/services/sync/voyager.service.ts, src/mobile-services.json
=> fix: bump voyager-client version

src/app/app.component.html, src/app/pages/devicetrust/devicetrust.page.html, src/app/pages/profile/profile.page.html
In order to simplify the E2E tests, we should have some useful IDs inside ionic-showcase. This PR: https://github.com/aerogear/test-suite/pull/17 is an example of how this IDs could help the QE team write E2E tests.
=> IDs for automated E2E tests

server/src/index.js
=> fix: exit on unhandled rejection

src/app/services/auth.service.ts
User profile loading is failing. Currently the code uses raw keycloak-js to load the user profile, but our sdk has a promisified version for this function [1].
[1] https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/auth/src/Auth.ts#L49
=> fix: user profile loading

.circleci/config.yml
In order to fix the e2e pipeline I have:
* removed package.json check
* removed cordova plugins cache
* removed npm cache
1. https://circleci.com/workflow-run/6ce6ac9b-f810-4547-ba0f-5b711b1a5231
=> Fix package.json verification

README.adoc, server/package.json, server/scripts/keycloak/initKeycloak.js
=> fix: issues with keycloak config

README.adoc, server/package.json, server/scripts/keycloak/getToken.js, server/scripts/keycloak/initKeycloak.js
- Fix the init keycloak script outputting the wrong content
- Add getToken script for GraphQL playground header
=> fix: amend keycloak helper scripts

server/src/index.js
Fixes the problem where refreshing any non index page (e.g. tasks page) gives a 404 error.
=> fix: issue where refreshing pwa causes 404

.circleci/config.yml
Production build enables PWA capabilities
=> chore: Use prod build for showcase container

server/src/index.js
Reverts aerogear/ionic-showcase#290
CC @darahayes
=> Revert "fix: issue where refreshing pwa causes 404"

README.adoc
See: https://github.com/aerogear/ionic-showcase/issues/293
=> Docs: Keycloak config clarifications

README.adoc, server/scripts/keycloak/initKeycloak.js
Should fix https://github.com/aerogear/ionic-showcase/issues/293
=> fix: wrong keycloak config was printed by helper script

devfile.yaml
=> fix: add initial devfile for codeready

client/src/auth/KeycloakRoute.tsx, client/src/auth/keycloakAuth.ts, client/src/components/Header.tsx, client/src/components/OfflineQueueBadge.tsx, client/src/components/Router.tsx, client/src/components/Task.tsx, client/src/pages/TaskPage.tsx
=> fix: routing issues

package.json, scripts/create_walkthrough.sh
Simple script for creating walkthough branch automatically. 
This means we do not need to keep 2 branches up to date and control stable version on walkthough branch and have master unstable.
=> fix: script for creating wt

README.adoc
=> doc: tweaks to the README

server/src/auth.ts
=> fix: proper keycloak import

client/package.json, client/src/components/Header.tsx, client/src/components/NetworkBadge.tsx, client/src/components/OfflineList.tsx, client/src/components/TaskList.tsx, client/src/config/WebNetworkStatus.ts, client/src/config/clientConfig.ts, client/src/helpers/utils.ts, client/src/hooks/useNetworkStatus.ts, client/src/hooks/useOfflineMutation.ts, client/src/pages/AddTaskPage.tsx, client/src/pages/TaskPage.tsx, client/src/pages/UpdateTaskPage.tsx, server/src/data/MongoDBDataProvider.ts, server/src/graphql.ts
- Landing page now loads when server is down
- Fix React memory leak due to network listeners in useNetworkStatus hook
- Fix uncaught errors in useOfflineMutation hook
- Fix error where server was returning previous value for update queries
=> Client bug fixes

server/src/auth.ts
This reverts invalid changes I have made for the session.
Review is not required.
=> fix: Restore session on the server in order to use playground

.circleci/config.yml, README.adoc, client/package.json, client/public/index.html, client/public/manifest.json, package.json, scripts/publish_container.sh, server/scripts/keycloak/initKeycloak.js, server/src/config/config.ts
Designed as extension for dockerized config. 
This was already verified by building things manually:
Repository name
https://hub.docker.com/repository/docker/aerogear/datasync-starter/tags?page=1
=> Add docker builds

.circleci/config.yml, README.adoc, client/package.json, client/public/index.html, client/public/manifest.json, client/src/auth/keycloakAuth.ts, client/src/config/clientConfig.ts, package.json, scripts/publish_container.sh, server/scripts/keycloak/initKeycloak.js, server/src/config/config.ts
Motivation #346 
Run server for all of the flavours
1. cd client && yarn dev
2. Verify that localhost server is being used and client connects to server
1. cd client && yarn start
2. Verify that localhost server is being used and client connects to server
1. Go to the server/config/config.ts and change port to any other value
We are doing it to make sure that we not using default port that is hardcoded in the app.
2. Execute `yarn prepare:client` 
3. Restart server and use server side link to 
4. Verify that app is calling the same server port rather than hardcoded one
=> Enable dockerized config

client/src/App.tsx
I have two small questions.
1. Should we put all the setup for the listener into its own hook/file, or are we happy to keep it in the App.tsx file?
2. Any suggestions on the actual wording that will be displayed?
=> feat: show toast when conflicts occur

client/package.json, devfile.yaml, server/src/db.ts, server/src/index.ts, walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc, walkthroughs/2-exploring-datasync-local/walkthrough.adoc
Move to app namespace when serving client from server
=> Move to app namespace

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc
Update instructions for keycloak
=> Minor fixes for wt

client/ionic.config.json, client/package.json, server/package.json
fix: issues with the app related to graphback update
=> Fix crashing example

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc, walkthroughs/2-exploring-datasync-local/walkthrough.adoc
Review changes in the walkthrough
=> fix: Walkthrough review

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc
Adding more info (as documentation above do not mention graphback etc.)
=> fix: Add more information to walkthough

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc
=> fix: wording/grammar in the walkthrough

devfile.yaml, walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc
=> fix: generate command

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc
=> fix: WT keycloak issues

client/src/config/clientConfig.ts, client/src/helpers/CapacitorNetworkStatus.ts, package.json
=> Capacitor listener

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc
=> fix: samle query and mutation for playground step in wt

walkthroughs/1-exploring-datasync-codeready/walkthrough.adoc, walkthroughs/2-exploring-datasync-local/disabled_walkthrough.adoc
fixed the walkthrough links so they don't throw a 404 when you open them.
=> fix: OSD docs link in walkthrough 

client/src/pages/ProfilePage.tsx, client/src/pages/TaskPage.tsx, server/.env
* Logout button wasn't working because `isOnline` wasn't being passed down. It was always showing the `you are offline error`. It's not a big deal but do we even need to check that? You should be able to log out while offline IMO.
* Logged in user's name was being displayed as two first names
=> Minor fixes

devfile.yaml
=> fix: devfile update for CRW 2.1
